In [1]:
import torch
import face_alignment
from skimage import io

In [2]:
torch.__version__

'2.1.0+cu121'

In [3]:
torch.cuda.is_available()

True

In [7]:
## 2d landmark detection
fa = face_alignment.FaceAlignment(
    face_alignment.LandmarksType.TWO_D, 
    flip_input=False,
    face_detector='sfd',    # support detectors ['dlib', 'blazeface']
    dtype=torch.bfloat16, device='cuda',
    )

img_path = "image.png"
input = io.imread(img_path)
preds = fa.get_landmarks(input) # a list

In [12]:
preds[0].shape

(68, 2)

In [15]:
preds[0][0]

array([356., 254.], dtype=float32)

In [13]:
## 3d landmark detection
fa_3d = face_alignment.FaceAlignment(face_alignment.LandmarksType.THREE_D, flip_input=False)

input = io.imread(img_path)
preds_3d = fa_3d.get_landmarks(input)

Downloading: "https://www.adrianbulat.com/downloads/python-fan/3DFAN4-4a694010b9.zip" to /local/home/yaqqin/.cache/torch/hub/checkpoints/3DFAN4-4a694010b9.zip
100%|██████████| 91.9M/91.9M [00:01<00:00, 94.2MB/s]
Downloading: "https://www.adrianbulat.com/downloads/python-fan/depth-6c4283c0e0.zip" to /local/home/yaqqin/.cache/torch/hub/checkpoints/depth-6c4283c0e0.zip
100%|██████████| 224M/224M [00:02<00:00, 96.2MB/s] 


In [14]:
preds_3d[0].shape

(68, 3)

In [16]:
preds_3d[0][0]

array([351.     , 254.     , -66.67276], dtype=float32)

In [20]:
preds[0] == preds_3d[0][:, :2]

array([[False,  True],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [ True,  True],
       [False,  True],
       [ True, False],
       [ True, False],
       [False, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False,  True],
       [False,  True],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [False, False],
       [False,  True],
       [False, False],
       [False,  True],
       [False,  True],
       [ True,  True],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [False, False],
       [False,  True],
       [ True,  True],
       [False,  True],
       [ True,  True],
       [ True, False],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True, False],
       [Fal

In [23]:
import numpy as np
np.max(preds_3d[0], axis = 0)

array([618.     , 464.     ,  82.69811], dtype=float32)

In [26]:
np.linalg.norm(preds[0]-preds_3d[0][:, :2]) ** 2 / 68

26.132350894273472

In [27]:
preds[0][0]

array([356., 254.], dtype=float32)

In [28]:
preds_3d[0][0]

array([351.     , 254.     , -66.67276], dtype=float32)

In [31]:

type(preds[0][0][0])

numpy.float32

In [33]:
import cv2 
img = cv2.imread("image.png")
img.shape

(1358, 958, 3)

In [34]:
img = cv2.imread("datasets/multiface/minidataset/m--20180227--0000--6795937--GHS/images/E061_Lips_Puffed/400016/023404.png")
img.shape

(2048, 1334, 3)